✨ Add metadata only to template language
lsaudon/l10nization pull request #228
Opened 2023-06-16 21:48 UTC by RobertOdrowaz

Resolves #227 

FYI I wasn't able to run the tests because of some weird error
```
[vscode.php]: One or more snippets from the extension 'php' very likely confuse snippet-variables and snippet-placeholders (see https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax for more details)
Unexpected token '}', "}^��qV6$"... is not valid JSON
Error: Cannot find module '/home/robert/Documents/l10nization/out/test/suite/index'
```

2023-06-19 07:13 UTC, lsaudon commented
Wow, thanks for your contribution.
I'll try to look at that later today.

2023-06-19 10:29 UTC, lsaudon commented
Thank you very much, I didn't know that wasn't necessary.
I don't think I'm the only one.
I assume that's also the case for the description?

End-to-end tests are broken.
I'm only running unit tests at the moment 😞  `npm run unit-test`

2023-06-19 10:33 UTC, lsaudon requested changes

2023-06-19 10:33 UTC, lsaudon commented on src/test/suite/toJson.spec.ts
> +        true,
replace `true` to `false`

2023-06-19 10:33 UTC, lsaudon commented on src/test/suite/toJson.spec.ts
> +        true,
replace `true` to `false`

2023-06-19 10:33 UTC, lsaudon commented on src/test/suite/toJson.spec.ts
> +  it('should return json when message with description for tempate file', () => {
`template` to `template`

2023-06-19 22:09 UTC, RobertOdrowaz commented
I've fixed the tests.

I don't think that placeholders and description only in template file is explicitly stated anywhere in the documentation. It can be found in the generator code itself https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/localizations/gen_l10n_types.dart#L343
```dart
description = _description(templateBundle.resources, resourceId, isResourceAttributeRequired),
placeholders = _placeholders(templateBundle.resources, resourceId, isResourceAttributeRequired),
```
both description and placeholders take only `templateBundle` argument.

As a sidenote there is a comment above `Message` class is incorrect stating that every entry should have corresponding @ entry in the template file which clearly isn't true.
```dart
// The template ARB file must contain an entry called @myResourceId for each
// message named myResourceId. The @ entry describes message parameters
// called "placeholders" and can include an optional description.
// Here's a simple example message with no parameters:
```

2023-06-20 07:40 UTC, lsaudon approved these changes

2023-06-20 07:40 UTC, merged